server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: james2017
    url: jdbc:mysql://127.0.0.1:3306/hello
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: mysql
      mode: always


